//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogoConceptos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalogoConceptos()
        {
            this.archivosFotograficos = new HashSet<archivosFotograficos>();
            this.ejecucionesMensuales = new HashSet<ejecucionesMensuales>();
            this.estimaciones = new HashSet<estimaciones>();
            this.relacionConceptosMateriales = new HashSet<relacionConceptosMateriales>();
            this.requisiciones = new HashSet<requisiciones>();
            this.requisicionesMateriales = new HashSet<requisicionesMateriales>();
            this.requisicionesParciales = new HashSet<requisicionesParciales>();
        }
    
        public int idConcepto { get; set; }
        public string clave { get; set; }
        public string descripcion { get; set; }
        public string unidad { get; set; }
        public Nullable<double> precioUnitario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<archivosFotograficos> archivosFotograficos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ejecucionesMensuales> ejecucionesMensuales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estimaciones> estimaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relacionConceptosMateriales> relacionConceptosMateriales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requisiciones> requisiciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requisicionesMateriales> requisicionesMateriales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requisicionesParciales> requisicionesParciales { get; set; }
    }
}
