//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlPagos
    {
        public int idRequisicionParcial { get; set; }
        public int noDocumento { get; set; }
        public Nullable<int> idRequisicion { get; set; }
        public string clDocumento { get; set; }
        public Nullable<double> importe { get; set; }
        public Nullable<System.DateTime> fechaDocumento { get; set; }
        public Nullable<int> docCompensacion { get; set; }
        public Nullable<System.DateTime> fechaCompensacion { get; set; }
        public string factura { get; set; }
        public Nullable<int> usuarioCreacion { get; set; }
        public Nullable<int> usuarioCompensacion { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
    }
}
