//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sgopEntities : DbContext
    {
        public sgopEntities()
            : base("name=sgopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<archivosFotograficos> archivosFotograficos { get; set; }
        public virtual DbSet<catalogoConceptos> catalogoConceptos { get; set; }
        public virtual DbSet<catalogoEmpresas> catalogoEmpresas { get; set; }
        public virtual DbSet<catalogoEstatus> catalogoEstatus { get; set; }
        public virtual DbSet<catalogoMateriales> catalogoMateriales { get; set; }
        public virtual DbSet<catalogoMunicipios> catalogoMunicipios { get; set; }
        public virtual DbSet<catalogoRoles> catalogoRoles { get; set; }
        public virtual DbSet<catalogoSistemas> catalogoSistemas { get; set; }
        public virtual DbSet<controlCobros> controlCobros { get; set; }
        public virtual DbSet<controlPagos> controlPagos { get; set; }
        public virtual DbSet<ejecucionesMensuales> ejecucionesMensuales { get; set; }
        public virtual DbSet<estimaciones> estimaciones { get; set; }
        public virtual DbSet<licitaciones> licitaciones { get; set; }
        public virtual DbSet<proyectos> proyectos { get; set; }
        public virtual DbSet<rangos> rangos { get; set; }
        public virtual DbSet<relacionConceptosMateriales> relacionConceptosMateriales { get; set; }
        public virtual DbSet<relacionSistemasRoles> relacionSistemasRoles { get; set; }
        public virtual DbSet<requisiciones> requisiciones { get; set; }
        public virtual DbSet<requisicionesMateriales> requisicionesMateriales { get; set; }
        public virtual DbSet<requisicionesParciales> requisicionesParciales { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
