//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos
    {
        public int idProyecto { get; set; }
        public Nullable<int> idLicitacion { get; set; }
        public Nullable<int> idEstatus { get; set; }
        public Nullable<System.DateTime> fechaContrato { get; set; }
        public string polizaAnticipo { get; set; }
        public string polizaVicios { get; set; }
        public string policaCumplimiento { get; set; }
        public Nullable<int> plazoDias { get; set; }
        public Nullable<System.DateTime> fechaInicioContrato { get; set; }
        public Nullable<System.DateTime> fechaFinalContrato { get; set; }
        public Nullable<System.DateTime> fechaInicioReal { get; set; }
        public Nullable<System.DateTime> fechaFinalReal { get; set; }
        public string actaEntrega { get; set; }
        public Nullable<int> jefeObra { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> usuarioCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<int> usuarioModificacion { get; set; }
    
        public virtual catalogoEstatus catalogoEstatus { get; set; }
        public virtual licitaciones licitaciones { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
        public virtual usuarios usuarios2 { get; set; }
    }
}
