//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class relacionSistemasRoles
    {
        public int idRelacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idSistema { get; set; }
        public Nullable<int> idRol { get; set; }
    
        public virtual catalogoRoles catalogoRoles { get; set; }
        public virtual catalogoSistemas catalogoSistemas { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
